# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf382f11d55ae6bfe89ba165640ff2472c48feb50adafdea09c08c3224313e3842273bb9e64e1d9fd83a1be4a655bbee016345a50158b2266f9ecf8604d8c4ba

test:
  secret_key_base: a46fbcd67d875a9f6d423700247a62615ce3c9ba74284e0b7c644e0b71eaa8b6821ed8fd1a8c1f29cf67291b77197340b56c08fd700aaf9388ed149525e54642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
